PL/Controllers/CargoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;

namespace PL.Controllers
{
    public class CargoController : Controller
    {
        // GET: CargoCargaMasiva


        [HttpGet]
        public ActionResult GetAll()
        {
            ML.Cargo cargo = new ML.Cargo();
            


            ML.Result result = BL.Cargo.GetAll();

            if (result.Correct)
            {
                cargo.Cargos = result.Objects;
                
            }
            else
            {
                ViewBag.Message = "Ocurrio un error al traer la información";
            }

            return View(cargo);
        }

        [HttpGet]
        public ActionResult CargaMasiva()
        {
            //ML.Cargo cargo = new ML.Cargo()
            ML.ErrorExcel errorExcel = new ML.ErrorExcel();

            errorExcel.Errores = new List<object>();
            errorExcel.Cargo = new ML.Cargo();


            ML.Result result = BL.Cargo.GetAll();

            if (Session["RutaExcel"] != null)
            {
                errorExcel.Cargo.Cargos = result.Objects;
                errorExcel.Correct = true;
            }

            return View(errorExcel);
        }

        [HttpPost]
        public ActionResult CargaMasiva(ML.ErrorExcel errorItem)
        {
            if (Session["RutaExcel"] != null) //Que ya tiene la ruta del archivo
            {
                string direccionExcel = (string)Session["RutaExcel"];
                string CadenaConexion = System.Configuration.ConfigurationManager.AppSettings["ConexionExcel"].ToString();
                string ConnectionString = CadenaConexion + direccionExcel;


                ML.Result resultDataTable = BL.Cargo.ConvertToDataTable(direccionExcel, ConnectionString);

                if (resultDataTable.Correct)
                {
                    string ErrorMessage = " ";
                    DataTable tableCargo = (DataTable)resultDataTable.Object;//unboxing
                    foreach (DataRow row in tableCargo.Rows)
                    {
                        ML.Cargo cargo = new ML.Cargo();

                        cargo.id = row[0].ToString();
                        cargo.name = row[1].ToString();
                        cargo.company_id = row[2].ToString();
                        cargo.amount = decimal.Parse(row[3].ToString()).ToString();
                        cargo.status = row[4].ToString();
                        cargo.created_at = row[5].ToString();
                        cargo.paid_at = row[6].ToString();


                        ML.Result resultCargo = BL.Cargo.Add(cargo);

                        if (!resultCargo.Correct)
                        {
                            ErrorMessage += resultCargo.ErrorMessage;
                        }
                    }

                    if (ErrorMessage == "")
                    {
                        ViewBag.Message = "Los cargos han sido cargados correctamente";
                    }
                    else
                    {
                        ViewBag.Message = "Ocurrió un error al insertar los cargos" + ErrorMessage;
                    }

                }

                //Cargar el archivo
            }
            else
            {
                //Validar el archivo
                HttpPostedFileBase file = Request.Files["ExcelCargos"];

                if (file.ContentLength > 0)//Si el usuario seleccionó un excel
                {
                    string extension = Path.GetExtension(file.FileName).ToLower();
                    if (extension == ".csv")
                    {
                        string direccionExcel = Server.MapPath("~/ExcelCargaMasiva/") + Path.GetFileNameWithoutExtension(file.FileName) + '-' + DateTime.Now.ToString("yyyyMMddHHmmss") + ".csv";

                        if (!System.IO.File.Exists(direccionExcel))
                        {
                           
                            try
                            {

                                file.SaveAs(direccionExcel);
                                Session["RutaExcel"] = direccionExcel;
                                string CadenaConexion = System.Configuration.ConfigurationManager.AppSettings["ConexionExcel"].ToString();
                                string ConnectionString = CadenaConexion + direccionExcel;

                                //.Result resultDataTable = BL.Cargo.ConvertToDataTable(direccionExcel, ConnectionString);
                                ML.Result resultDataTable = BL.Cargo.ReadPersons(direccionExcel);

                                if (resultDataTable.Correct)
                                {
                                    DataTable tableCargo = (DataTable)resultDataTable.Object;//unboxing
                                    ML.Result resultValidarExcel = BL.Cargo.ValidarExcel(tableCargo);
                                    if (!resultValidarExcel.Correct) //si hubo errores
                                    {
                                        ML.ErrorExcel error = new ML.ErrorExcel();
                                        error.Errores = resultValidarExcel.Objects;
                                        return View(error);
                                    }
                                    else
                                    {
                                        ViewBag.Message = "Todos los registros han sido validados correctamente, puede proceder a cargarlos";
                                    }
                                }

                            }
                            catch (Exception ex)
                            {
                                ViewBag.Message = ex.Message;
                            }

                        }
                        else
                        {
                            ViewBag.Message = "Ya existe el nombre del archivo, por favor renombrarlo";
                        }

                    }
                    else
                    {
                        ViewBag.Message = "Seleccione un archivo con extensión .xlsx";
                    }
                }
                else
                {
                    ViewBag.Message = "Seleccione un archivo";
                }
            }
            return PartialView("ValidationModal");
        }

        //protected void ImportCSV(object sender, EventArgs e)
        //{
        //    //Upload and save the file
        //    string csvPath = Server.MapPath("~/Files/") + Path.GetFileName(FileUpload1.PostedFile.FileName);
        //    FileUpload1.SaveAs(csvPath);

        //    //Create a DataTable.
        //    DataTable dt = new DataTable();
        //    dt.Columns.AddRange(new DataColumn[5] { new DataColumn("Id", typeof(int)),
        //    new DataColumn("Name", typeof(string)),
        //    new DataColumn("Technology", typeof(string)),
        //    new DataColumn("Company", typeof(string)),
        //    new DataColumn("Country",typeof(string)) });

        //    //Read the contents of CSV file.
        //    string csvData = File.ReadAllText(csvPath);

        //    //Execute a loop over the rows.
        //    foreach (string row in csvData.Split('\n'))
        //    {
        //        if (!string.IsNullOrEmpty(row))
        //        {
        //            dt.Rows.Add();
        //            int i = 0;

        //            //Execute a loop over the columns.
        //            foreach (string cell in row.Split(','))
        //            {
        //                dt.Rows[dt.Rows.Count - 1][i] = cell;
        //                i++;
        //            }
        //        }
        //    }

        //    //Bind the DataTable.
        //    GridView1.DataSource = dt;
        //    GridView1.DataBind();
        //}
    }
}

PL/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PL.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

PL/Views/Cargo/CargaMasiva.cshtml
@model ML.ErrorExcel
@{
    ViewBag.Title = "CargaMasiva";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Carga Masiva</h2>

<div class="container">
    <div class="row">

    </div>

</div>
@using (Html.BeginForm("CargaMasiva", "Cargo", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="col-md-3">
        <input type="file" id="fuEmpleados" name="ExcelCargos" />
    </div>
    if (!Model.Correct)
    {
        <div class="col-md-1">
            <input type="submit" value="Procesar" class="btn btn-info" />
        </div>
    }
    else
    {
        <div class="col-md-1">
            <input type="submit" value="IniciarCarga" class="btn btn-success" />
        </div>
    }
}

@if (Model.Errores.Count > 0)
{
    <table class="table table-bordered table-responsive">
        <thead>
            <tr>
                <td>Registro</td>
                <td>Error</td>

            </tr>
        </thead>
        <tbody>
            @foreach (ML.ErrorExcel error in Model.Errores)
            {
                <tr>
                    <td>@error.IdRegistro</td>
                    <td>@error.Message</td>
                </tr>
            }



        </tbody>
    </table>
}

@Scripts.Render("~/bundles/jquery")

PL/Views/Cargo/GetAll.cshtml
@model ML.Cargo
@{
    ViewBag.Title = "GetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script src="../../Scripts/jquery-1.10.2.js" type="text/javascript"></script>
<script src="../../Scripts/jquery-1.10.2.min.js" type="text/javascript"></script>

<div class="container">
    <div class="row">
        <h2>Cargo</h2>
    </div>


    <div class="row">
        <div class="col-md-12">
            <h5>Lista de cargos.</h5>
            <hr />
        </div>
    </div>



    <table class="table table-bordered table-responsive">
        <thead>
            <tr>
                <td class="text-center" style=" font-weight:bold;">Editar</td>

                <td class="text-center" style=" font-weight:bold;">id</td>
                <td class="text-center" style=" font-weight:bold;">company_name</td>
                <td class="text-center" style=" font-weight:bold;">company_id</td>
                <td class="text-center" style=" font-weight:bold;">amount</td>
                <td class="text-center" style=" font-weight:bold;">status</td>
                <td class="text-center" style=" font-weight:bold;">created_at</td>
                <td class="text-center" style=" font-weight:bold;">updated_at</td>


                <td class="text-center" style=" font-weight:bold;">Eliminar</td>
            </tr>
        </thead>

        <tbody>
            @foreach (ML.Cargo cargo in Model.Cargos)
            {
                <tr>
                    <td class="text-center"><a class="btn btn-warning glyphicon glyphicon-edit" href="@Url.Action("Form", "Empleado", new { Id = cargo.id })"></a></td>

                    <td>@cargo.id</td>
                    <td class="text-center">@cargo.company_name</td>
                    <td>@cargo.company_id</td>
                    <td class="text-center">@cargo.amount</td>
                    <td class="text-center">@cargo.status</td>
                    <td class="text-center">@cargo.created_at</td>
                    <td class="text-center">@cargo.updated_at</td>

                    <td class="text-center"><a class="btn btn-danger glyphicon glyphicon-trash" href="@Url.Action("Delete", "Empleado", new { Id = cargo.id })" onclick="return confirm('Estas seguro que deseas eliminar este registro?');"></a></td>
                </tr>
            }
        </tbody>
    </table>

</div>

@Scripts.Render("~/bundles/jquery")

<script type="text/javascript">

    $(document).ready(function () {

        $("#ddlEmpresa").change(function () {

            $("#ddlEmpresa").empty();

            $.ajax({
                type: 'POST',
                url: '@Url.Action("GetDepartamento")',
                data: { IdArea: $("#ddlArea").val() },
                success: function (departamentos) {


                    $.each(departamentos, function (i, departamentos) {
                        $("#ddlDepartamento").append('<option value="'
                            + departamentos.IdDepartamento + '">'
                            + departamentos.Nombre + '</option>');
                    });
                },
                error: function (ex) {
                    alert('Failed. ' + ex);
                }
            });
        });
    })
</script>

PL/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

PL/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

PL/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

PL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Cargo", "GetAll", "Cargo")</li>
                    <li>@Html.ActionLink("Cargar archivo", "CargaMasiva", "Cargo")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>